### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by gumkyy** [yamori813/pic32mx_i2s_sin#1]
Processing chipkit_dp32 (platform: microchippic32; board: chipkit_dp32; framework: arduino; board_build.f_cpu: 8000000L; build_flags: -IC:/microchip_solutions_v2013-06-15/USB/, -IC:/microchip_solutions_v2013-06-15/Microchip/Include/, -IC:/microchip_solutions_v2013-06-15/Microchip/USB/)
---------------------------------------------------------------------------------------------------------- 
CONFIGURATION: https://docs.platformio.org/page/boards/microchippic32/chipkit_dp32.html
PLATFORM: Microchip PIC32 1.6.0 > Digilent chipKIT DP32
HARDWARE: 32MX250F128B 8MHz, 32KB RAM, 120KB Flash
PACKAGES: framework-arduinomicrochippic32 1.20006.0 (2.0.6), toolchain-microchippic32 1.40803.143 (4.8.3)  
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 29 compatible libraries
Scanning dependencies...
No dependencies
work-arduinomicrochippic32\cores\pic32\cpp-startup.S -Wl,--script=chipKIT-application-32MX250F128.ld -Wl,--script=chipKIT-application-COMMON.ld .pio\build\chipkit_dp32\src\config.c.o .pio\build\chipkit_dp32\src\crt0.S.o .pio\build\chipkit_dp32\src\i2c.c.o .pio\build\chipkit_dp32\src\i2s.c.o .pio\build\chipkit_dp32\src\main.c.o .pio\build\chipkit_dp32\src\sbrk.c.o .pio\build\chipkit_dp32\src\usb_descriptors.c.o .pio\build\chiwork-arduinomicrochippic32\cores\pic32\cpp-startup.S -Wl,--script=chipKIT-application-32MX250F128.ld -Wl,--script=chipKIT-application-COMMON.ld .pio\build\chipkit_dp32\src\config.c.o .pio\build\chipkit_dp32\src\crt0.S.o .pio\build\chipkit_dp32\src\i2c.c.o .pio\build\chipkit_dp32\src\i2s.c.o .pio\build\chipkit_dp32\src\main.c.o .pio\build\chipkit_dp32\src\sbrk.c.o .pio\build\chipkit_dp32\src\usb_descriptors.c.o .pio\build\chipkit_dp32\src\usb_function_audio.c.o -L.pio\build\chipkit_dp32 -LC:\Users\User\appdata\roaming\spb_data\.platformio\packages\framework-arduinomicrochippic32\cores\pic32 -LC:\Users\User\appdata\roaming\spb_data\.platformio\packages\framework-arduinomicrochippic32\variants\DP32 -Wl,--start-group .pio\build\chipkit_dp32\libFrameworkArduinoVariant.a .pio\build\chipkit_dp32\libFrameworkArduino.a -lm -Wl,--end-group
c:\users\User\appdata\roaming\spb_data\.platformio\packages\toolchain-microchippic32\bin\bin\gcc\pic32mx\4.8.3\..\..\..\..\bin/pic32-ld.exe: MPIDE Version not specfied correctly
c:\users\User\appdata\roaming\spb_data\.platformio\packages\toolchain-microchippic32\bin\bin\gcc\pic32mx\4.8.3\..\..\..\..\bin/pic32-ld.exe: Link terminated due to previous error(s).
collect2.exe: error: ld returned 255 exit status
*** [.pio\build\chipkit_dp32\firmware.elf] Error 255

**Comment by yamori813** [comment]
This is not platformio project. I use Pinguino gcc by make. Also use Microchip library. I remember some header pproblem in plastformio this project.

If you will try to port  platformio this project. I am very well glad.

**Comment by gumkyy** [comment]
I'll try to...
